// oxlint-disable-next-line typescript/triple-slash-reference -- pulls the ambient virtual-module types into consumer programs
/// <reference path="../virtual.d.ts" />

import {
  annotationCollisions as initialCollisions,
  annotationsByPath as initialAnnotations,
  mentionsByPath as initialMentions,
} from "virtual:oblik-annotations";
import { scenes as initialScenes } from "virtual:oblik-catalog";
import { sceneLoaders as initialLoaders } from "virtual:oblik-loaders";

import type { DuplicateId, OblikSceneEntry } from "../source/catalog";
import { batchHmr } from "./hmr-batch";
import type { AnnotationBundle, MentionBundle, SceneLoaderMap } from "./Host";
import { mountOblik } from "./Host";
import { sceneLoaderKeys } from "./loader-keys";

/** The `virtual:oblik-annotations` module's shape. */
type AnnotationsModule = {
  annotationsByPath: AnnotationBundle;
  annotationCollisions: DuplicateId[];
  mentionsByPath: MentionBundle;
};

/**
 * The `virtual:oblik-*` modules are generated by our own Vite plugin, but HMR
 * hands them over as Vite's opaque module namespace — a bag of exports, read by
 * key. Each field is read through a shape check rather than a blind assertion:
 * that check is what keeps a plugin change from surfacing as a crash inside
 * `setScenes` (or, worse, as a scene list that is quietly not an array).
 */
function catalogScenes(mod: object): OblikSceneEntry[] | undefined {
  const scenes = Reflect.get(mod, "scenes");
  return Array.isArray(scenes) ? scenes : undefined;
}

function annotationsModule(mod: object): AnnotationsModule | undefined {
  const annotationsByPath = Reflect.get(mod, "annotationsByPath");
  const annotationCollisions = Reflect.get(mod, "annotationCollisions");
  const mentionsByPath = Reflect.get(mod, "mentionsByPath");
  if (!annotationsByPath || !annotationCollisions || !mentionsByPath) return undefined;
  return { annotationsByPath, annotationCollisions, mentionsByPath };
}

function loaderMap(mod: object): SceneLoaderMap | undefined {
  const loaders = Reflect.get(mod, "sceneLoaders");
  return loaders ?? undefined;
}

export type BootstrapOpts = {
  el?: HTMLElement;
};

/** Zero-config entry point: mounts the host on the initial catalog and keeps it fresh over HMR. */
export function bootstrap(opts: BootstrapOpts = {}): void {
  const host = mountOblik({
    el: opts.el ?? document.getElementById("app")!,
    scenes: initialScenes,
    loaders: initialLoaders,
    annotations: initialAnnotations,
    mentions: initialMentions,
    collisions: initialCollisions,
  });

  if (import.meta.hot) {
    // One accept per dep: the callback only ever sees the freshly fetched
    // module. A combined multi-dep accept would fire on every update and
    // re-import unchanged deps, which hits the browser's module cache and
    // resurrects stale catalog/annotation state.
    //
    // Each accept skips no-op updates (same content as last seen), so one
    // scene edit only invalidates downstream memos when something changed.
    let lastScenes = JSON.stringify(initialScenes);
    import.meta.hot.accept("virtual:oblik-catalog", (mod) => {
      if (!mod) return;
      const scenes = catalogScenes(mod);
      if (!scenes) return;
      const next = JSON.stringify(scenes);
      if (next === lastScenes) return;
      lastScenes = next;
      batchHmr(() => host.setScenes(scenes));
    });
    let lastAnnotations = JSON.stringify([initialAnnotations, initialMentions, initialCollisions]);
    import.meta.hot.accept("virtual:oblik-annotations", (mod) => {
      if (!mod) return;
      const fresh = annotationsModule(mod);
      if (!fresh) return;
      const next = JSON.stringify([
        fresh.annotationsByPath,
        fresh.mentionsByPath,
        fresh.annotationCollisions,
      ]);
      if (next === lastAnnotations) return;
      lastAnnotations = next;
      batchHmr(() => {
        host.setAnnotations(fresh.annotationsByPath);
        host.setCollisions(fresh.annotationCollisions);
        host.setMentions(fresh.mentionsByPath);
      });
    });
    let lastLoaders = sceneLoaderKeys(initialLoaders);
    import.meta.hot.accept("virtual:oblik-loaders", (mod) => {
      if (!mod) return;
      const loaders = loaderMap(mod);
      if (!loaders) return;
      const next = sceneLoaderKeys(loaders);
      if (next === lastLoaders) return;
      lastLoaders = next;
      batchHmr(() => host.setLoaders(loaders));
    });
  }
}
